version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
        environment:
          RAILS_ENV: test
    steps:
      # コードのチェックアウト
      - checkout

      
          
      - run:
          name: heroku deploy # push方式でアップしている。アプリ本体はサブディレクトリに有るのでsubtreeやprefix指定する
          command: |
            gem install bundler -v 1.17.3 # version明記
            rm Gemfile.lock # Gemdile.lockがgemのversionを明記しているため、一旦削除
            bundle install
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME_STAGING.git master
          
      